# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development: &default
  adapter: mysql2
  database: sample_app    
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  user_name: root
  password: rami
  socket: /var/run/mysqld/mysqld.sock

#test:
 # <<: *default
  #database: toy_app
test:
  adapter: mysql2
  database: sample_app_test
  username: root
  password: rami
  host: localhost

 #test:
  #adapter: mysql2
  #database: toy_app     
  #encoding: utf8
  #min_messages: warning
  #pool: 5
  #timeout: 5000
  #user_name: root
  #password: rami
  #socket: /var/run/mysqld/mysqld.sock

production:
  <<: *default
  database: db/production.sqlite3
